platform :ios, '15.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'QuranEngineApp' do
  pod 'Texture'
end

post_install do |installer|
  installer.pods_project.frameworks_group["iOS"]["AssetsLibrary.framework"].remove_from_project
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
