included:
  - BatchDownloader
  - QueuePlayer
  - Quran
  - SQLitePersistence
  - UIKitExtension
  - VFoundation

disabled_rules:
  - cyclomatic_complexity
  - colon
  - empty_count

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  #NOT NEEDED - conditional_returns_on_newline
  - empty_count
  - explicit_init
  #NOT NEEDED -explicit_type_interface
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - number_separator
  - object_literal
  #DISABLED until https://github.com/realm/SwiftLint/issues/1497 operator_usage_whitespace
  - overridden_super_call
  #NOT NEEDED - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  #NOT NEEDED - switch_case_on_newline

type_name:
  max_length: 60
  
identifier_name:
  min_length: 1
  max_length: 60
  
file_length: 600

line_length: 150 # Needs to configure it correctly!

type_body_length: 300 

function_parameter_count: 10

function_body_length: 80

large_tuple: 4

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  Quran
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/
                    \/\/  Quran for iOS is a Quran reading application for iOS\.
                    \/\/  Copyright \(C\) 2017  Quran\.com
                    \/\/
                    \/\/  This program is free software: you can redistribute it and/or modify
                    \/\/  it under the terms of the GNU General Public License as published by
                    \/\/  the Free Software Foundation, either version 3 of the License, or
                    \/\/  \(at your option\) any later version\.
                    \/\/
                    \/\/  This program is distributed in the hope that it will be useful,
                    \/\/  but WITHOUT ANY WARRANTY; without even the implied warranty of
                    \/\/  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\.  See the
                    \/\/  GNU General Public License for more details\.
                    \/\/
