# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Android2iOS-Localization' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Android2iOS-Localization
pod 'AEXML', '~> 4.2.2'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_INSTALL_NAME_BASE'] = target.product_name
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
        end
    end
end
