///
/// @Generated by Mockolo
///

import Foundation
import PromiseKit
@testable import QuranTextKit
import TranslationService

class LocalTranslationsRetrieverMock: QuranTextKit.LocalTranslationsRetriever {
    init() { }

    private(set) var getLocalTranslationsCallCount = 0
    var getLocalTranslationsHandler: (() -> (Promise<[Translation]>))?
    func getLocalTranslations() -> Promise<[Translation]> {
        getLocalTranslationsCallCount += 1
        if let getLocalTranslationsHandler = getLocalTranslationsHandler {
            return getLocalTranslationsHandler()
        }
        fatalError("getLocalTranslationsHandler returns can't have a default value thus its handler must be set")
    }
}
