# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPad Pro (9.7-inch)",
  "iPad Pro (10.5-inch)",
  "iPad Pro (11-inch)",
  "iPad Pro (12.9-inch)",
  "iPad Pro (12.9-inch) (3rd generation)",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X",
  "iPhone XS Max",
  "iPhone SE",
])

# The name of the scheme which contains the UI Tests
scheme("Quran")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(false)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
