name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Package:
    runs-on: macos-26
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setting up Xcode
      run: sudo xcode-select -s "/Applications/Xcode_26.2.app"

    - name: Install xcbeautify
      run: brew install xcbeautify

    - name: Run tests
      run: make test-no-sync

    - uses: codecov/codecov-action@a99c28d3f0da835de33ff2feb2e15691c7b9641f # v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  PackageSync:
    runs-on: macos-26
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setting up Xcode
      run: sudo xcode-select -s "/Applications/Xcode_26.2.app"

    - name: Install xcbeautify
      run: brew install xcbeautify

    - name: Run tests
      run: make test-sync

  ExampleApp:
    runs-on: macos-26
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setting up Xcode
        run: sudo xcode-select -s "/Applications/Xcode_26.2.app"

      - name: Install xcbeautify
        run: brew install xcbeautify
      
      - name: Build
        run: make build-example-no-sync

  ExampleAppSync:
    runs-on: macos-26
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setting up Xcode
        run: sudo xcode-select -s "/Applications/Xcode_26.2.app"

      - name: Install xcbeautify
        run: brew install xcbeautify
      
      - name: Build
        run: make build-example-sync

  SwiftFormat:
    runs-on: macos-26
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setting up Xcode
        run: sudo xcode-select -s "/Applications/Xcode_26.2.app"
      
      - name: SwiftFormat
        run: make format-lint
